### ISSUE TITLE
Get a 401 Unauthorized response for /sync-roles-permissions/roles

### ISSUE THREAD

**Issue by ghostspook** [alan2207/strapi-plugin-sync-roles-permissions#2]
When I click on the _Export Roles And Permissions_ button I get a 401 Unauthorized response. The UI then logs me out and prompts me for the Ui.

![imagen](https://user-images.githubusercontent.com/8203762/115966801-d22be680-a4f4-11eb-9437-8255ae8deffd.png)

![imagen](https://user-images.githubusercontent.com/8203762/115966895-42d30300-a4f5-11eb-9cf0-4d8dd131c483.png)

## How to reproduce the error:

I have strapi running in a docker setup.

1. Install strapi using docker according to oficial documentation:
https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html
2. When the app is built, visit localhost:1337/admin, create an admin user, create a simple  content-type (say article) and give the Authenticated Role some permissions on that new content-type.
3. Using docker desktop, open a CLI terminal
![imagen](https://user-images.githubusercontent.com/8203762/115967186-bfb2ac80-a4f6-11eb-86a7-8479bd08aea6.png)
4. Install the plugin and rebuild using the plug-in instructions:
https://github.com/alan2207/strapi-plugin-sync-roles-permissions#installation
5. When it's done, restart the docker app.
6. Login with as the admin user and try to export using the _Export Roles and Permissions_ button.

**UPDATE:** I just noticed that, after installing the plugin using npm (as per instructions) there are only 2 files modified in my project: `package.json` and `package-lock.json`. I see no additional folders/files in the `./app/api` folder. So I suppose the 401 Unauthorized error is due to the fact that the required API is not properly setup. Am I wrong?

**Comment by alan2207** [comment]
Hey @ghostspook what message do you get in the 401 response?

You can try override the plugin by doing this:

-create this file: `extensions/sync-roles-permissions/controllers/sync-roles-permissions.js`
- copy all the content from [here](https://github.com/alan2207/strapi-plugin-sync-roles-permissions/blob/master/controllers/sync-roles-permissions.js)

- disable/comment out the code from L44 to L46:
```js
if (user.roles[0].id != 1) {
  return ctx.unauthorized("You must be admin to access this resource!");
}
```

if it works with the disabled code my assumption is that maybe your role id is not 1, which is why it doesn't pass this check. you can try to log your user's role id.

Let me know if it helped!

Update: I updated the check, so it will check the role name to be `Super Admin` instead of id, go ahead and install v0.4.1 and try it out.

**Comment by ghostspook** [comment]
Hi @alan2207 , thanks for the quick reply.

This is the message I obtained.

```
{
"statusCode":401,
"error":"Unauthorized",
"message":"You must be admin to access this resource!"
}
```

I tried overriding `extensions/sync-roles-permissions/controllers/sync-roles-permissions.js`but it gave me a 500 Server Error instead of the 401. I noticed you made a new version 0.4.1  so I updated it.

I noticed a little syntax error in `services/sync-roles-permissions.js` which brought down strapi but after fixing it I was able to get it running and I can now export and sync the roles. So, I finally forked the repo, fixed the syntax typo and made a pull request.

Thank you. Great plugin!
